package com.magaran.svalidator.testing.extensions.validation

import com.magaran.svalidator.testing.exceptions.ValidationTestingException
import com.magaran.svalidator.testing.extensions.common.ShouldBeValidWithDataContinuationExtensions
import com.magaran.svalidator.testing.extensions.common.ShouldMessageKeyContinuation
import com.magaran.svalidator.testing.extensions.validation
import com.magaran.svalidator.validation.Invalid
import com.magaran.svalidator.validation.ResultWithoutData
import com.magaran.svalidator.validation.Valid
import com.magaran.svalidator.FieldKey

package object functional {

  private def eitherToResultWithoutData(either: Either[Invalid, ?]): ResultWithoutData =
    either match
      case Left(invalid) => Invalid(invalid.validationFailures)
      case Right(_)      => Valid

  /** Provides extensions for testing validation summaries generated by functional validators */
  extension [A](summary: Either[Invalid, A])

    /** Throws an exception if at least one failure occurred in this validation summary. */
    infix def shouldBeValid: ShouldBeValidWithDataContinuationExtensions[A] =
      summary match
        case Left(Invalid(validationFailures)) =>
          throw ValidationTestingException(
            "\nExpected instance to be valid, but it had the following errors:\n%s"
              .format(validationFailures.map(_.message).mkString("\n"))
          )
        case Right(data) => ShouldBeValidWithDataContinuationExtensions(data)

    /** Throws an exception if no errors occurred for the given field name in this summary */
    infix def shouldHaveValidationErrorFor(fieldName: String): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(eitherToResultWithoutData(summary), fieldName)

    /** Throws an exception if no errors occurred for the given FieldKey in this summary */
    infix def shouldHaveValidationErrorFor(targetKey: FieldKey): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(eitherToResultWithoutData(summary), targetKey)

    /** Throws an exception if an error occurred for the given field name in this summary */
    infix def shouldNotHaveValidationErrorFor(fieldName: String): Unit =
      validation.shouldNotHaveValidationErrorFor(eitherToResultWithoutData(summary), fieldName)

    /** Throws an exception if an error occurred for the given FieldKey in this summary */
    infix def shouldNotHaveValidationErrorFor(targetKey: FieldKey): Unit =
      validation.shouldNotHaveValidationErrorFor(eitherToResultWithoutData(summary), targetKey)
}
