package com.magaran.svalidator.testing.extensions.validation
import com.magaran.svalidator.testing.exceptions.ValidationTestingException
import com.magaran.svalidator.testing.extensions
import com.magaran.svalidator.testing.extensions.common.ShouldMessageKeyContinuation
import com.magaran.svalidator.testing.extensions.validation
import com.magaran.svalidator.validation.Invalid
import com.magaran.svalidator.validation.ResultWithoutData
import com.magaran.svalidator.validation.Valid
import com.magaran.svalidator.FieldKey

package object withoutdata {

  /** Provides extensions for testing validation summaries generated by validators */
  extension (summary: ResultWithoutData)

    /** Throws an exception if at least one failure occurred in this validation summary. */
    def shouldBeValid(): Unit =
      summary match
        case Invalid(validationFailures) =>
          throw ValidationTestingException(
            "\nExpected instance to be valid, but it had the following errors:\n%s"
              .format(validationFailures.map(_.message).mkString("\n"))
          )
        case Valid =>

    /** Throws an exception if no errors occurred for the given field name in this summary */
    infix def shouldHaveValidationErrorFor(fieldName: String): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(summary, fieldName)

    /** Throws an exception if no errors occurred for the given FieldKey in this summary */
    infix def shouldHaveValidationErrorFor(targetKey: FieldKey): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(summary, targetKey)

    /** Throws an exception if an error occurred for the given field name in this summary */
    infix def shouldNotHaveValidationErrorFor(fieldName: String): Unit =
      validation.shouldNotHaveValidationErrorFor(summary, fieldName)

    /** Throws an exception if an error occurred for the given FieldKey in this summary */
    infix def shouldNotHaveValidationErrorFor(targetKey: FieldKey): Unit =
      validation.shouldNotHaveValidationErrorFor(summary, targetKey)
}
