package com.magaran.svalidator.testing.extensions.validation

import com.magaran.svalidator.testing.exceptions.ValidationTestingException
import com.magaran.svalidator.testing.extensions
import com.magaran.svalidator.testing.extensions.common.ShouldBeValidWithDataContinuationExtensions
import com.magaran.svalidator.testing.extensions.common.ShouldMessageKeyContinuation
import com.magaran.svalidator.testing.extensions.validation
import com.magaran.svalidator.validation.Invalid
import com.magaran.svalidator.validation.ResultWithSuccessData
import com.magaran.svalidator.validation.Valid
import com.magaran.svalidator.FieldKey

package object withdata {

  /** Provides extensions for testing validation summaries generated by validators */
  extension [A](summary: ResultWithSuccessData[A])

    /** Throws an exception if at least one failure occurred in this validation summary. */
    infix def shouldBeValid: ShouldBeValidWithDataContinuationExtensions[A] =
      summary match
        case Invalid(validationFailures) =>
          throw ValidationTestingException(
            "\nExpected instance to be valid, but it had the following errors:\n%s"
              .format(validationFailures.map(_.message).mkString("\n"))
          )
        case Valid(data) => ShouldBeValidWithDataContinuationExtensions(data)

    /** Throws an exception if no errors occurred for the given field name in this summary */
    infix def shouldHaveValidationErrorFor(fieldName: String): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(summary.withoutData, fieldName)

    /** Throws an exception if no errors occurred for the given FieldKey in this summary */
    infix def shouldHaveValidationErrorFor(targetKey: FieldKey): ShouldMessageKeyContinuation =
      validation.shouldHaveValidationErrorFor(summary.withoutData, targetKey)

    /** Throws an exception if an error occurred for the given field name in this summary */
    infix def shouldNotHaveValidationErrorFor(fieldName: String): Unit =
      validation.shouldNotHaveValidationErrorFor(summary.withoutData, fieldName)

    /** Throws an exception if an error occurred for the given FieldKey in this summary */
    infix def shouldNotHaveValidationErrorFor(targetKey: FieldKey): Unit =
      validation.shouldNotHaveValidationErrorFor(summary.withoutData, targetKey)
}
